# ShizishanGPT Configuration File

# Project Settings
project:
  name: "ShizishanGPT"
  version: "0.1.0"
  description: "Agricultural AI Assistant with ReAct Reasoning"

# Data Paths
data:
  raw: "data/raw"
  processed: "data/processed"
  embeddings: "data/embeddings"
  pdfs: "data/raw/pdfs"
  csvs: "data/raw/csvs"
  images: "data/raw/images"

# Model Paths
models:
  yield_predictor: "models/yield_predictor/model.pkl"
  pest_detector: "models/pest_detector/model.pth"
  weather_model: "models/weather_model/model.pth"
  llm: "models/llm/model.pth"
  rag_index: "models/rag/faiss_index"

# Yield Prediction Model
yield_model:
  algorithm: "random_forest"  # or "mlp"
  features:
    - "nitrogen"
    - "phosphorus"
    - "potassium"
    - "rainfall"
    - "temperature"
    - "ph"
  target: "yield"
  test_size: 0.2
  random_state: 42

# Pest Detection Model
pest_model:
  architecture: "resnet50"  # or "resnet18", "efficientnet"
  num_classes: 10
  image_size: [224, 224]
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  augmentation: true

# Weather Impact Model
weather_model:
  architecture: "lstm"
  sequence_length: 30
  hidden_size: 128
  num_layers: 2
  dropout: 0.2
  batch_size: 64
  epochs: 100

# RAG Configuration
rag:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  chunk_size: 512
  chunk_overlap: 50
  top_k: 5
  similarity_threshold: 0.7
  vector_store: "faiss"  # or "chroma"

# LLM Configuration
llm:
  model_name: "gpt2"  # or custom model path
  max_length: 512
  temperature: 0.7
  top_p: 0.9
  top_k: 50

# ReAct Configuration
react:
  max_iterations: 10
  tools:
    - "yield_predictor"
    - "pest_detector"
    - "weather_model"
    - "rag_retriever"
  verbose: true

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: true

# Frontend Configuration
frontend:
  framework: "streamlit"  # or "gradio"
  port: 8501
  theme: "light"

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
